image: gradle:6.1.1-jdk13

services:
  - mysql:latest

stages:
  - build
  - validate
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_DATABASE: "oopp"
  MYSQL_ROOT_PASSWORD: "pwd"
  MYSQL_HOST: "mysql"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

server-build:
  stage: build
  script:
    gradle --build-cache :server:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

server-checkstyle:
  stage: validate
  script: gradle :server:checkstyleMain :server:checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

server-test:
  stage: test
  script:
    gradle :server:test
